name: divvy
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - ruff>=0.0.137
  - sqlalchemy>=2.0.0
  - pip
  - pip:
    - python-dotenv>=1.0.0
