name: cli
description: A command-line utility designed to help groups track and split shared expenses fairly.
version: 0.0.1
repository: https://github.com/alyiox/divvy.git
publish_to: none

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  built_collection: ^5.1.1
  collection: ^1.19.1
  dio: ^5.9.0
  intl: ^0.20.2
  divvy_api_client:
    path: lib/src/generated/api/divvy

dev_dependencies:
  build_runner: ^2.4.13
  derry: ^1.5.0
  lints: ^6.0.0
  test: ^1.25.6

scripts:
  build: dart run build_runner build --delete-conflicting-outputs --verbose
